<?php

/**
 * USDA SR Legacy / Foundation approximate values per 100g edible portion.
 * Used to estimate recipe macros. Always treat results as estimates.
 *
 * @see https://fdc.nal.usda.gov/
 */
return [
    'chicken_breast_cooked' => ['name_en' => 'Chicken breast, grilled', 'name_ar' => 'صدر دجاج مشوي', 'kcal' => 165, 'protein' => 31.0, 'carbs' => 0.0, 'fats' => 3.6],
    'chicken_thigh_cooked' => ['name_en' => 'Chicken thigh, roasted, skinless', 'name_ar' => 'فخذ دجاج بدون جلد', 'kcal' => 179, 'protein' => 24.8, 'carbs' => 0.0, 'fats' => 8.2],
    'turkey_breast' => ['name_en' => 'Turkey breast, roasted', 'name_ar' => 'صدر ديك رومي', 'kcal' => 135, 'protein' => 30.1, 'carbs' => 0.0, 'fats' => 0.7],
    'lean_beef_cooked' => ['name_en' => 'Beef, lean, grilled', 'name_ar' => 'لحم بقري قليل الدهن', 'kcal' => 250, 'protein' => 26.0, 'carbs' => 0.0, 'fats' => 15.0],
    'lamb_lean_cooked' => ['name_en' => 'Lamb, lean, roasted', 'name_ar' => 'لحم غنم قليل الدهن', 'kcal' => 206, 'protein' => 28.0, 'carbs' => 0.0, 'fats' => 9.5],
    'fish_white_cooked' => ['name_en' => 'White fish, baked', 'name_ar' => 'سمك أبيض مشوي', 'kcal' => 128, 'protein' => 24.0, 'carbs' => 0.0, 'fats' => 2.7],
    'salmon_cooked' => ['name_en' => 'Salmon, baked', 'name_ar' => 'سلمون مشوي', 'kcal' => 206, 'protein' => 22.1, 'carbs' => 0.0, 'fats' => 12.4],
    'shrimp_cooked' => ['name_en' => 'Shrimp, cooked', 'name_ar' => 'روبيان مطبوخ', 'kcal' => 99, 'protein' => 24.0, 'carbs' => 0.2, 'fats' => 0.3],
    'tuna_canned_water' => ['name_en' => 'Tuna, canned in water', 'name_ar' => 'تونة بالماء', 'kcal' => 86, 'protein' => 19.0, 'carbs' => 0.0, 'fats' => 1.0],
    'egg_whole' => ['name_en' => 'Egg, whole, boiled', 'name_ar' => 'بيض مسلوق', 'kcal' => 155, 'protein' => 12.6, 'carbs' => 1.1, 'fats' => 10.6],
    'egg_white' => ['name_en' => 'Egg white, cooked', 'name_ar' => 'بياض بيض', 'kcal' => 52, 'protein' => 10.9, 'carbs' => 0.7, 'fats' => 0.2],
    'labneh' => ['name_en' => 'Labneh (strained yogurt)', 'name_ar' => 'لبنة', 'kcal' => 140, 'protein' => 8.0, 'carbs' => 5.0, 'fats' => 10.0],
    'greek_yogurt_nonfat' => ['name_en' => 'Greek yogurt, nonfat', 'name_ar' => 'زبادي يوناني خالي الدسم', 'kcal' => 59, 'protein' => 10.2, 'carbs' => 3.6, 'fats' => 0.4],
    'yogurt_lowfat' => ['name_en' => 'Yogurt, low fat', 'name_ar' => 'زبادي قليل الدسم', 'kcal' => 63, 'protein' => 5.3, 'carbs' => 7.0, 'fats' => 1.6],
    'milk_lowfat' => ['name_en' => 'Milk, 1%', 'name_ar' => 'حليب قليل الدسم', 'kcal' => 42, 'protein' => 3.4, 'carbs' => 5.0, 'fats' => 1.0],
    'cottage_cheese_lowfat' => ['name_en' => 'Cottage cheese, low fat', 'name_ar' => 'جبن قريش قليل الدسم', 'kcal' => 72, 'protein' => 12.4, 'carbs' => 2.7, 'fats' => 1.0],
    'feta_light' => ['name_en' => 'Feta cheese', 'name_ar' => 'جبنة فيتا', 'kcal' => 264, 'protein' => 14.2, 'carbs' => 4.1, 'fats' => 21.3],
    'halloumi' => ['name_en' => 'Halloumi cheese', 'name_ar' => 'جبنة حلوم', 'kcal' => 321, 'protein' => 21.0, 'carbs' => 2.2, 'fats' => 25.0],
    'rice_white_cooked' => ['name_en' => 'White rice, cooked', 'name_ar' => 'أرز أبيض مطبوخ', 'kcal' => 130, 'protein' => 2.7, 'carbs' => 28.2, 'fats' => 0.3],
    'rice_brown_cooked' => ['name_en' => 'Brown rice, cooked', 'name_ar' => 'أرز بني مطبوخ', 'kcal' => 123, 'protein' => 2.7, 'carbs' => 25.6, 'fats' => 1.0],
    'bulgur_cooked' => ['name_en' => 'Bulgur, cooked', 'name_ar' => 'برغل مطبوخ', 'kcal' => 83, 'protein' => 3.1, 'carbs' => 18.6, 'fats' => 0.2],
    'quinoa_cooked' => ['name_en' => 'Quinoa, cooked', 'name_ar' => 'كينوا مطبوخة', 'kcal' => 120, 'protein' => 4.4, 'carbs' => 21.3, 'fats' => 1.9],
    'oats_dry' => ['name_en' => 'Oats, dry', 'name_ar' => 'شوفان', 'kcal' => 389, 'protein' => 16.9, 'carbs' => 66.3, 'fats' => 6.9],
    'whole_wheat_bread' => ['name_en' => 'Whole wheat bread', 'name_ar' => 'خبز قمح كامل', 'kcal' => 247, 'protein' => 13.0, 'carbs' => 41.3, 'fats' => 3.4],
    'pita_whole_wheat' => ['name_en' => 'Pita, whole wheat', 'name_ar' => 'خبز عربي أسمر', 'kcal' => 266, 'protein' => 9.8, 'carbs' => 55.0, 'fats' => 2.6],
    'freekeh_cooked' => ['name_en' => 'Freekeh, cooked', 'name_ar' => 'فريكة مطبوخة', 'kcal' => 141, 'protein' => 5.0, 'carbs' => 26.0, 'fats' => 2.0],
    'lentils_cooked' => ['name_en' => 'Lentils, cooked', 'name_ar' => 'عدس مطبوخ', 'kcal' => 116, 'protein' => 9.0, 'carbs' => 20.1, 'fats' => 0.4],
    'chickpeas_cooked' => ['name_en' => 'Chickpeas, cooked', 'name_ar' => 'حمص مطبوخ', 'kcal' => 164, 'protein' => 8.9, 'carbs' => 27.4, 'fats' => 2.6],
    'fava_beans_cooked' => ['name_en' => 'Fava beans, cooked', 'name_ar' => 'فول مطبوخ', 'kcal' => 110, 'protein' => 7.6, 'carbs' => 19.7, 'fats' => 0.4],
    'black_beans_cooked' => ['name_en' => 'Black beans, cooked', 'name_ar' => 'فاصوليا سوداء', 'kcal' => 132, 'protein' => 8.9, 'carbs' => 23.7, 'fats' => 0.5],
    'hummus' => ['name_en' => 'Hummus', 'name_ar' => 'حمص بالطحينة', 'kcal' => 166, 'protein' => 7.9, 'carbs' => 14.3, 'fats' => 9.6],
    'olive_oil' => ['name_en' => 'Olive oil', 'name_ar' => 'زيت زيتون', 'kcal' => 884, 'protein' => 0.0, 'carbs' => 0.0, 'fats' => 100.0],
    'tahini' => ['name_en' => 'Tahini', 'name_ar' => 'طحينة', 'kcal' => 595, 'protein' => 17.0, 'carbs' => 21.2, 'fats' => 53.8],
    'tomato' => ['name_en' => 'Tomato, raw', 'name_ar' => 'طماطم', 'kcal' => 18, 'protein' => 0.9, 'carbs' => 3.9, 'fats' => 0.2],
    'cucumber' => ['name_en' => 'Cucumber, raw', 'name_ar' => 'خيار', 'kcal' => 15, 'protein' => 0.7, 'carbs' => 3.6, 'fats' => 0.1],
    'lettuce' => ['name_en' => 'Lettuce, raw', 'name_ar' => 'خس', 'kcal' => 15, 'protein' => 1.4, 'carbs' => 2.9, 'fats' => 0.2],
    'onion' => ['name_en' => 'Onion, raw', 'name_ar' => 'بصل', 'kcal' => 40, 'protein' => 1.1, 'carbs' => 9.3, 'fats' => 0.1],
    'garlic' => ['name_en' => 'Garlic, raw', 'name_ar' => 'ثوم', 'kcal' => 149, 'protein' => 6.4, 'carbs' => 33.1, 'fats' => 0.5],
    'bell_pepper' => ['name_en' => 'Bell pepper, raw', 'name_ar' => 'فلفل رومي', 'kcal' => 31, 'protein' => 1.0, 'carbs' => 6.0, 'fats' => 0.3],
    'spinach' => ['name_en' => 'Spinach, raw', 'name_ar' => 'سبانخ', 'kcal' => 23, 'protein' => 2.9, 'carbs' => 3.6, 'fats' => 0.4],
    'broccoli' => ['name_en' => 'Broccoli, cooked', 'name_ar' => 'بروكلي', 'kcal' => 35, 'protein' => 2.4, 'carbs' => 7.2, 'fats' => 0.4],
    'zucchini' => ['name_en' => 'Zucchini, cooked', 'name_ar' => 'كوسا', 'kcal' => 15, 'protein' => 1.1, 'carbs' => 2.7, 'fats' => 0.4],
    'eggplant' => ['name_en' => 'Eggplant, cooked', 'name_ar' => 'باذنجان', 'kcal' => 35, 'protein' => 0.8, 'carbs' => 8.7, 'fats' => 0.2],
    'carrot' => ['name_en' => 'Carrot, raw', 'name_ar' => 'جزر', 'kcal' => 41, 'protein' => 0.9, 'carbs' => 9.6, 'fats' => 0.2],
    'potato_boiled' => ['name_en' => 'Potato, boiled', 'name_ar' => 'بطاطس مسلوقة', 'kcal' => 87, 'protein' => 1.9, 'carbs' => 20.1, 'fats' => 0.1],
    'sweet_potato' => ['name_en' => 'Sweet potato, baked', 'name_ar' => 'بطاطا حلوة', 'kcal' => 90, 'protein' => 2.0, 'carbs' => 20.7, 'fats' => 0.2],
    'mixed_vegetables' => ['name_en' => 'Mixed vegetables, cooked', 'name_ar' => 'خضار مشكلة', 'kcal' => 65, 'protein' => 2.9, 'carbs' => 13.1, 'fats' => 0.3],
    'avocado' => ['name_en' => 'Avocado', 'name_ar' => 'أفوكادو', 'kcal' => 160, 'protein' => 2.0, 'carbs' => 8.5, 'fats' => 14.7],
    'banana' => ['name_en' => 'Banana', 'name_ar' => 'موز', 'kcal' => 89, 'protein' => 1.1, 'carbs' => 22.8, 'fats' => 0.3],
    'apple' => ['name_en' => 'Apple', 'name_ar' => 'تفاح', 'kcal' => 52, 'protein' => 0.3, 'carbs' => 13.8, 'fats' => 0.2],
    'orange' => ['name_en' => 'Orange', 'name_ar' => 'برتقال', 'kcal' => 47, 'protein' => 0.9, 'carbs' => 11.8, 'fats' => 0.1],
    'dates' => ['name_en' => 'Dates, Deglet Noor', 'name_ar' => 'تمر', 'kcal' => 282, 'protein' => 2.5, 'carbs' => 75.0, 'fats' => 0.4],
    'raisins' => ['name_en' => 'Raisins', 'name_ar' => 'زبيب', 'kcal' => 299, 'protein' => 3.1, 'carbs' => 79.2, 'fats' => 0.5],
    'almonds' => ['name_en' => 'Almonds', 'name_ar' => 'لوز', 'kcal' => 579, 'protein' => 21.2, 'carbs' => 21.6, 'fats' => 49.9],
    'walnuts' => ['name_en' => 'Walnuts', 'name_ar' => 'جوز', 'kcal' => 654, 'protein' => 15.2, 'carbs' => 13.7, 'fats' => 65.2],
    'peanuts' => ['name_en' => 'Peanuts', 'name_ar' => 'فول سوداني', 'kcal' => 567, 'protein' => 25.8, 'carbs' => 16.1, 'fats' => 49.2],
    'honey' => ['name_en' => 'Honey', 'name_ar' => 'عسل', 'kcal' => 304, 'protein' => 0.3, 'carbs' => 82.4, 'fats' => 0.0],
    'lemon_juice' => ['name_en' => 'Lemon juice', 'name_ar' => 'عصير ليمون', 'kcal' => 22, 'protein' => 0.4, 'carbs' => 6.9, 'fats' => 0.2],
    'parsley' => ['name_en' => 'Parsley', 'name_ar' => 'بقدونس', 'kcal' => 36, 'protein' => 3.0, 'carbs' => 6.3, 'fats' => 0.8],
    'mint' => ['name_en' => 'Mint', 'name_ar' => 'نعناع', 'kcal' => 44, 'protein' => 3.3, 'carbs' => 8.4, 'fats' => 0.7],
    'coriander' => ['name_en' => 'Coriander (cilantro)', 'name_ar' => 'كزبرة', 'kcal' => 23, 'protein' => 2.1, 'carbs' => 3.7, 'fats' => 0.5],
    'tomato_sauce' => ['name_en' => 'Tomato sauce', 'name_ar' => 'صلصة طماطم', 'kcal' => 24, 'protein' => 1.2, 'carbs' => 5.3, 'fats' => 0.3],
    'broth_chicken' => ['name_en' => 'Chicken broth', 'name_ar' => 'مرق دجاج', 'kcal' => 15, 'protein' => 1.0, 'carbs' => 1.0, 'fats' => 0.5],
    'okras' => ['name_en' => 'Okra, cooked', 'name_ar' => 'بامية', 'kcal' => 22, 'protein' => 1.9, 'carbs' => 4.5, 'fats' => 0.2],
    'green_beans' => ['name_en' => 'Green beans, cooked', 'name_ar' => 'فاصوليا خضراء', 'kcal' => 35, 'protein' => 1.9, 'carbs' => 7.9, 'fats' => 0.3],
    'cabbage' => ['name_en' => 'Cabbage, cooked', 'name_ar' => 'ملفوف', 'kcal' => 23, 'protein' => 1.3, 'carbs' => 5.5, 'fats' => 0.1],
    'mushroom' => ['name_en' => 'Mushrooms, cooked', 'name_ar' => 'فطر', 'kcal' => 28, 'protein' => 2.2, 'carbs' => 5.3, 'fats' => 0.5],
    'corn' => ['name_en' => 'Corn, cooked', 'name_ar' => 'ذرة', 'kcal' => 96, 'protein' => 3.4, 'carbs' => 21.0, 'fats' => 1.5],
    'peas' => ['name_en' => 'Green peas, cooked', 'name_ar' => 'بازلاء', 'kcal' => 84, 'protein' => 5.4, 'carbs' => 15.6, 'fats' => 0.2],
];
